# Generated by Django 3.2.4 on 2021-06-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=20)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'WebUser',
                'verbose_name_plural': 'WebUser',
                'ordering': ['id'],
            },
        ),
    ]
