# Generated by Django 3.2.4 on 2021-06-20 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=30)),
                ('video_address', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.webuser')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('share_id', models.AutoField(primary_key=True, serialize=False)),
                ('user1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='front.webuser')),
                ('user2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='front.webuser')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.video')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_word', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.webuser')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.video')),
            ],
        ),
    ]
